/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import main.itemManDBP;
import main.itemManipulation;
import main.searchDBP;

/**
 *
 * @author engeer
 */
public class InventoryP extends javax.swing.JFrame {

    /** Creates new form InventoryP */
    public InventoryP() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        InventorySearchedListTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Search_jComboBoxI = new javax.swing.JComboBox<>();
        search_jTextFieldI = new javax.swing.JTextField();
        Search_jButton1I = new javax.swing.JButton();
        Update_jButton2 = new javax.swing.JButton();
        Delete_jButton3 = new javax.swing.JButton();
        Add_jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        InventorySearchedListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item_Serial", "Type", "Subtype", "Item_Name", "Stocks", "Price", "W.Price", "Expiry"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        InventorySearchedListTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(InventorySearchedListTable);

        jLabel1.setText("Search by:");

        Search_jComboBoxI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item name", "serial" }));

        Search_jButton1I.setText("Search");
        Search_jButton1I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_jButton1IActionPerformed(evt);
            }
        });

        Update_jButton2.setText("Update");
        Update_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_jButton2ActionPerformed(evt);
            }
        });

        Delete_jButton3.setText("Delete");
        Delete_jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_jButton3ActionPerformed(evt);
            }
        });

        Add_jButton4.setText("Add");
        Add_jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Search_jComboBoxI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_jTextFieldI, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Search_jButton1I)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Update_jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Delete_jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Add_jButton4)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Search_jComboBoxI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_jTextFieldI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_jButton1I)
                    .addComponent(Update_jButton2)
                    .addComponent(Delete_jButton3)
                    .addComponent(Add_jButton4)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Search_jButton1IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_jButton1IActionPerformed
        // TODO add your handling code here:
        String Types_comboBox = Search_jComboBoxI.getSelectedItem().toString();
        String Search_Key = search_jTextFieldI.getText();
        
        searchDBP a = new searchDBP();

        // Clear table
        a.clearTable(InventorySearchedListTable);
        try {
            a.searchByNameInventory(Types_comboBox, Search_Key, InventorySearchedListTable);

        } catch (SQLException ex) {
            Logger.getLogger(nMainFrameP.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_Search_jButton1IActionPerformed

    private void Update_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_jButton2ActionPerformed
        // TODO add your handling code here:
        //check selected
        itemManipulation iv = new itemManipulation();

        //check for selected row

        if(InventorySearchedListTable.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Select an item to update", "Select Item", JOptionPane.WARNING_MESSAGE);
        }else{
            //check and set for qty
            //set other table components
            int row = InventorySearchedListTable.getSelectedRow();
               // iv.setQty(Integer.parseInt(qty_textfield.getText()));
                iv.setItem_serial(Integer.valueOf(InventorySearchedListTable.getModel().getValueAt(row, 0).toString()));
                iv.setG_type(InventorySearchedListTable.getModel().getValueAt(row, 1).toString());
                iv.setS_type(InventorySearchedListTable.getModel().getValueAt(row, 2).toString());
                iv.setItem_name(InventorySearchedListTable.getModel().getValueAt(row, 3).toString());
                iv.setStock(Integer.valueOf(InventorySearchedListTable.getModel().getValueAt(row, 4).toString()));
                iv.setPrice((float) InventorySearchedListTable.getModel().getValueAt(row, 5));
                iv.setw_price((float) InventorySearchedListTable.getModel().getValueAt(row, 6));
                iv.setExpiry(InventorySearchedListTable.getModel().getValueAt(row, 7).toString());
                
              
                java.awt.EventQueue.invokeLater(() -> {
                        new InventoryUpdateFrame(iv,InventorySearchedListTable).setVisible(true);
                    });
   
                
        }
    }//GEN-LAST:event_Update_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Add_jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_jButton4ActionPerformed
        // TODO add your handling code here:
        int a=0;
        java.awt.EventQueue.invokeLater(() -> {
                        new InventoryUpdateFrame(a).setVisible(true);
                    });
        
    }//GEN-LAST:event_Add_jButton4ActionPerformed

    private void Delete_jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        itemManipulation iv = new itemManipulation();
        if(InventorySearchedListTable.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Select an item to update", "Select Item", JOptionPane.WARNING_MESSAGE);
        }else{
            //check and set for qty
            //set other table components
            int row = InventorySearchedListTable.getSelectedRow();
               // iv.setQty(Integer.parseInt(qty_textfield.getText()));
            iv.setItem_serial(Integer.valueOf(InventorySearchedListTable.getModel().getValueAt(row, 0).toString()));
            itemManDBP db = new itemManDBP();
            if (db.deleteInvBySerial(iv)){
            JOptionPane.showMessageDialog(null, "Update Complete. "
                                    + "Inventory update successful", 
                                    "Update Complete", JOptionPane.INFORMATION_MESSAGE);
            searchDBP a = new searchDBP();

        // Clear table
            a.clearTable(InventorySearchedListTable);
            
            }else{

            }
        }
        
    }//GEN-LAST:event_Delete_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_jButton4;
    private javax.swing.JButton Delete_jButton3;
    private javax.swing.JTable InventorySearchedListTable;
    private javax.swing.JButton Search_jButton1I;
    private javax.swing.JComboBox<String> Search_jComboBoxI;
    private javax.swing.JButton Update_jButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField search_jTextFieldI;
    // End of variables declaration//GEN-END:variables

}
