/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import java.sql.SQLException;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import main.CurrentOrdersP;

import main.itemManDBP;
import main.itemManipulation;
import main.panelSummaryP;
import main.searchDBP;

/**
 *
 * @author engeer
 */
public class nMainFrameP extends javax.swing.JFrame {

    /**
     * Creates new form nMainFrameP
     */
    public nMainFrameP() {
        initComponents();
        this.setLocationRelativeTo(null);
                CurrentOrdersP cOrders = CurrentOrdersP.getInstance();
                orderID_textArea.setText(cOrders.getOrder_id());
                customerID_textfield.setText(cOrders.getCustomer_id());
                panelSummaryP pSum = new panelSummaryP();

                try {
                    pSum.refreshSummaryTable(currentOrderListTable);
                    //                    panelSummary.setTotal();
                    pSum.setTotal(total_jLabel, netTotal_jLabel);
                     // Clear Search table and search bar
                    search_jTextField.setText("");
                    qty_textfield.setText("");
                    searchDBP searchTable = new searchDBP();
                    searchTable.clearTable(SearchedListTable);
                } catch (SQLException ex) {
                    System.out.println("nMainFrame add item "+ex);
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        currentOrderListTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        SearchedListTable = new javax.swing.JTable();
        OptionPanel = new javax.swing.JPanel();
        SummaryPanel = new javax.swing.JPanel();
        orderid_jLabel4 = new javax.swing.JLabel();
        customerID_jLabel5 = new javax.swing.JLabel();
        customerID_textfield = new javax.swing.JTextField();
        orderID_textArea = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        total_jLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tax_jToggleButton1 = new javax.swing.JToggleButton();
        tax_jLabel11 = new javax.swing.JLabel();
        Discount_jButton1 = new javax.swing.JButton();
        discount_jTextField = new javax.swing.JTextField();
        checkout_jButton = new javax.swing.JButton();
        netTotal_jLabel6 = new javax.swing.JLabel();
        netTotal_jLabel = new javax.swing.JLabel();
        Inventory_jButton1 = new javax.swing.JButton();
        Reports_jButton2 = new javax.swing.JButton();
        SearchPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Type_jComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        search_jTextField = new javax.swing.JTextField();
        search_jButton = new javax.swing.JButton();
        add_jButton = new javax.swing.JButton();
        del_jButton = new javax.swing.JButton();
        qty_textfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        wprice_jToggleButton1 = new javax.swing.JToggleButton();
        cancel_jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CUYI INK ENTERPRISE");
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        MainPanel.setBackground(new java.awt.Color(153, 153, 153));

        currentOrderListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "item_serial", "type", "sub type", "item_name", "qty", "price", "discount", "total price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        currentOrderListTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(currentOrderListTable);
        if (currentOrderListTable.getColumnModel().getColumnCount() > 0) {
            currentOrderListTable.getColumnModel().getColumn(0).setResizable(false);
            currentOrderListTable.getColumnModel().getColumn(0).setPreferredWidth(25);
            currentOrderListTable.getColumnModel().getColumn(1).setResizable(false);
            currentOrderListTable.getColumnModel().getColumn(1).setPreferredWidth(25);
            currentOrderListTable.getColumnModel().getColumn(2).setResizable(false);
            currentOrderListTable.getColumnModel().getColumn(2).setPreferredWidth(25);
            currentOrderListTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            currentOrderListTable.getColumnModel().getColumn(4).setResizable(false);
            currentOrderListTable.getColumnModel().getColumn(4).setPreferredWidth(5);
            currentOrderListTable.getColumnModel().getColumn(5).setResizable(false);
            currentOrderListTable.getColumnModel().getColumn(5).setPreferredWidth(5);
            currentOrderListTable.getColumnModel().getColumn(6).setResizable(false);
            currentOrderListTable.getColumnModel().getColumn(6).setPreferredWidth(15);
            currentOrderListTable.getColumnModel().getColumn(7).setResizable(false);
            currentOrderListTable.getColumnModel().getColumn(7).setPreferredWidth(15);
        }

        SearchedListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item_Serial", "Type", "Subtype", "Item_Name", "Stocks", "Price", "W.Price", "Expiry"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SearchedListTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(SearchedListTable);
        if (SearchedListTable.getColumnModel().getColumnCount() > 0) {
            SearchedListTable.getColumnModel().getColumn(0).setResizable(false);
            SearchedListTable.getColumnModel().getColumn(0).setPreferredWidth(5);
            SearchedListTable.getColumnModel().getColumn(1).setResizable(false);
            SearchedListTable.getColumnModel().getColumn(1).setPreferredWidth(15);
            SearchedListTable.getColumnModel().getColumn(2).setResizable(false);
            SearchedListTable.getColumnModel().getColumn(2).setPreferredWidth(15);
            SearchedListTable.getColumnModel().getColumn(3).setPreferredWidth(40);
            SearchedListTable.getColumnModel().getColumn(4).setResizable(false);
            SearchedListTable.getColumnModel().getColumn(4).setPreferredWidth(7);
            SearchedListTable.getColumnModel().getColumn(5).setResizable(false);
            SearchedListTable.getColumnModel().getColumn(5).setPreferredWidth(7);
            SearchedListTable.getColumnModel().getColumn(6).setResizable(false);
            SearchedListTable.getColumnModel().getColumn(6).setPreferredWidth(7);
            SearchedListTable.getColumnModel().getColumn(7).setResizable(false);
            SearchedListTable.getColumnModel().getColumn(7).setPreferredWidth(7);
        }

        OptionPanel.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout OptionPanelLayout = new javax.swing.GroupLayout(OptionPanel);
        OptionPanel.setLayout(OptionPanelLayout);
        OptionPanelLayout.setHorizontalGroup(
            OptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        OptionPanelLayout.setVerticalGroup(
            OptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        SummaryPanel.setBackground(new java.awt.Color(153, 204, 255));

        orderid_jLabel4.setText("Order ID:");

        customerID_jLabel5.setText("Customer ID:");

        customerID_textfield.setText("Customer");

        orderID_textArea.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Total");

        total_jLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        total_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        total_jLabel.setText("0.00");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("₱");

        tax_jToggleButton1.setText("Tax");
        tax_jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tax_jToggleButton1MouseClicked(evt);
            }
        });

        tax_jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tax_jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        Discount_jButton1.setBackground(new java.awt.Color(153, 204, 255));
        Discount_jButton1.setText("Discount");

        discount_jTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        checkout_jButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkout_jButton.setText("CHECKOUT");
        checkout_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkout_jButtonActionPerformed(evt);
            }
        });

        netTotal_jLabel6.setText("Net Total");

        netTotal_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        netTotal_jLabel.setText("0.00");

        Inventory_jButton1.setText("Inventory");
        Inventory_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inventory_jButton1ActionPerformed(evt);
            }
        });

        Reports_jButton2.setText("Reports");
        Reports_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reports_jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SummaryPanelLayout = new javax.swing.GroupLayout(SummaryPanel);
        SummaryPanel.setLayout(SummaryPanelLayout);
        SummaryPanelLayout.setHorizontalGroup(
            SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SummaryPanelLayout.createSequentialGroup()
                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SummaryPanelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkout_jButton)
                            .addGroup(SummaryPanelLayout.createSequentialGroup()
                                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Discount_jButton1)
                                    .addComponent(tax_jToggleButton1))
                                .addGap(41, 41, 41)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(discount_jTextField)
                            .addComponent(tax_jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(SummaryPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(SummaryPanelLayout.createSequentialGroup()
                                .addComponent(netTotal_jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(netTotal_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(SummaryPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(53, 53, 53)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(total_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                                .addGroup(SummaryPanelLayout.createSequentialGroup()
                                    .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(customerID_jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                        .addComponent(orderid_jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(orderID_textArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(customerID_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))))))
                    .addGroup(SummaryPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(Inventory_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(Reports_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addContainerGap())
        );
        SummaryPanelLayout.setVerticalGroup(
            SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SummaryPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(orderid_jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(orderID_textArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customerID_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(customerID_jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(total_jLabel))
                .addGap(18, 18, 18)
                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(netTotal_jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netTotal_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tax_jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tax_jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Discount_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discount_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(checkout_jButton)
                .addGap(49, 49, 49)
                .addGroup(SummaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reports_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Inventory_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SearchPanel.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setText("Select Type:");

        Type_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Paper", "Ink", "Vinyl", "Other Cons.", "Machines" }));
        Type_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Type_jComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Search");

        search_jButton.setText("Search");
        search_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_jButtonActionPerformed(evt);
            }
        });

        add_jButton.setText("Add");
        add_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_jButtonActionPerformed(evt);
            }
        });

        del_jButton.setText("Del");
        del_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_jButtonActionPerformed(evt);
            }
        });

        qty_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty_textfieldActionPerformed(evt);
            }
        });

        jLabel3.setText("qty:");

        wprice_jToggleButton1.setText("W");
        wprice_jToggleButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                wprice_jToggleButton1StateChanged(evt);
            }
        });
        wprice_jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wprice_jToggleButton1MouseClicked(evt);
            }
        });
        wprice_jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wprice_jToggleButton1ActionPerformed(evt);
            }
        });

        cancel_jButton.setText("Cancel");
        cancel_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Type_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_jButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qty_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wprice_jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add_jButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(del_jButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancel_jButton)
                .addGap(44, 44, 44))
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Type_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(search_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(del_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(qty_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wprice_jToggleButton1)
                    .addComponent(cancel_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(OptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 946, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SummaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SummaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wprice_jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wprice_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wprice_jToggleButton1ActionPerformed

    private void qty_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qty_textfieldActionPerformed

    private void del_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_jButtonActionPerformed
        // TODO add your handling code here:
        int rowDel = currentOrderListTable.getSelectedRow();
        
        if(currentOrderListTable.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Select an Item to Delete", "Select Item", JOptionPane.WARNING_MESSAGE);
        }else{
                    int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want"
                + " to delete this order entry?", "", JOptionPane.YES_NO_OPTION);

        itemManipulation delm = new itemManipulation();
        
        delm.setItem_serial(Integer.valueOf(currentOrderListTable.getModel().getValueAt(rowDel, 0).toString()));
        delm.setItem_name(currentOrderListTable.getModel().getValueAt(rowDel, 3).toString());
        delm.setG_type(currentOrderListTable.getModel().getValueAt(rowDel, 1).toString());
        delm.setS_type(currentOrderListTable.getModel().getValueAt(rowDel, 2).toString());
        delm.setQty((int) currentOrderListTable.getModel().getValueAt(rowDel, 4));
        delm.setSold_price((float)currentOrderListTable.getModel().getValueAt(rowDel,7));

        if ( choice == 0 ) {
                itemManDBP db = new itemManDBP();

                if ( db.deleteItem(  delm ) ) {
                    JOptionPane.showMessageDialog(null, "order entry is deleted", "",
                        JOptionPane.INFORMATION_MESSAGE);
                    
                  //adding back subtracted qty
                  if(db.addStockInventory(delm)){
//                            System.out.println("ok dagdag na sa inv");
                        }else{
                      
                            JOptionPane.showMessageDialog(null, "Problem adding order. "
                                    + "Please contact the administrator.", 
                                    "Something went wrong!", JOptionPane.ERROR_MESSAGE);
                        }
                  //  refreshSummaryTable();
                    panelSummaryP pSum = new panelSummaryP();
                    try {
                        pSum.refreshSummaryTable(currentOrderListTable);
                        pSum.setTotal(total_jLabel, netTotal_jLabel);
                                             // Clear Search table and search bar
                    search_jTextField.setText("");
                    qty_textfield.setText("");
                    searchDBP searchTable = new searchDBP();
                    searchTable.clearTable(SearchedListTable);
                    } catch (SQLException ex) {
                        System.out.println("deleting "+ ex);
                    }
                    //                    panelSummary.setTotal();
                    
                } else {
                    
                    JOptionPane.showMessageDialog(null, "Problem deleting order entry. Please contact the administrator.", "Something went wrong!", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

    }//GEN-LAST:event_del_jButtonActionPerformed

    private void  setSummaryNull(){
        discount_jTextField.setText("");
                tax_jLabel11.setText("");
                total_jLabel.setText("");
                        customerID_textfield.setText("");
                        orderID_textArea.setText("");
    }
    private void add_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_jButtonActionPerformed
        // adding order:
        CurrentOrdersP cOrders = CurrentOrdersP.getInstance();
        itemManipulation im = new itemManipulation();

        //check for selected row

        if(SearchedListTable.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Select an Item to Add", "Select Item", JOptionPane.WARNING_MESSAGE);
        }else{
            if(cOrders.getOrder_id() == null) {
                cOrders.setOrder_id();
                System.out.println("make id");
                orderID_textArea.setText(cOrders.getOrder_id());
            }
            else {
                System.out.println("current order: "+ cOrders.getOrder_id());
            }
            //check and set for qty
            //set other table components
            int row = SearchedListTable.getSelectedRow();
            try{
                
                im.setQty(Integer.parseInt(qty_textfield.getText()));
                im.setItem_serial(Integer.valueOf(SearchedListTable.getModel().getValueAt(row, 0).toString()));
                im.setCustomerId(customerID_textfield.getText());
                im.setG_type(SearchedListTable.getModel().getValueAt(row, 1).toString());
                im.setS_type(SearchedListTable.getModel().getValueAt(row, 2).toString());
                im.setItem_name(SearchedListTable.getModel().getValueAt(row, 3).toString());
                im.setStock(Integer.valueOf(SearchedListTable.getModel().getValueAt(row, 4).toString()));
                im.setPrice((float) SearchedListTable.getModel().getValueAt(row, 5));
                im.setw_price((float) SearchedListTable.getModel().getValueAt(row, 6));
                im.setExpiry(SearchedListTable.getModel().getValueAt(row, 7).toString());
                //checking if item is to be wholesaled
                if(wprice_jToggleButton1.isSelected()){
                    im.setWp_check(1);
                    wprice_jToggleButton1.setSelected(false);
                }else{
                    im.setWp_check(0);
                }

            }catch (NumberFormatException e){
                System.out.println("number exception "+ e);
                JOptionPane.showMessageDialog(null, "Qty is empty or not a number", "Qty", JOptionPane.WARNING_MESSAGE);
            }
            //im.setPrice(Integer.valueOf(SearchedListTable.getModel().getValueAt(row, 5).toString()));

                        itemManDBP additem = new itemManDBP();
            if ( additem.addOrderSales(im,cOrders) == true ) {
                //Subtract qty to stock inventory
                if(additem.subInventory(im)){
                    
                    //System.out.println("ok bawas na sa inv");
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Problem adding order. "
                            + "Please contact the administrator.", 
                            "Something went wrong!", JOptionPane.ERROR_MESSAGE);
                }
                //REFRESH SUMMARY ORDER TABLE
                
                panelSummaryP pSum = new panelSummaryP();

                try {
                    pSum.refreshSummaryTable(currentOrderListTable);
                    //                    panelSummary.setTotal();
                    pSum.setTotal(total_jLabel, netTotal_jLabel);
                     // Clear Search table and search bar
                    search_jTextField.setText("");
                    qty_textfield.setText("");
                    searchDBP searchTable = new searchDBP();
                    searchTable.clearTable(SearchedListTable);
                } catch (SQLException ex) {
                    System.out.println("nMainFrame add item "+ex);
                }
                

            } else {
                JOptionPane.showMessageDialog(null, "Problem adding order. Please contact the administrator.", "Something went wrong!", JOptionPane.ERROR_MESSAGE);
            }

        }//END check for selected row
    }//GEN-LAST:event_add_jButtonActionPerformed

    private void search_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_jButtonActionPerformed

        String Types_comboBox = Type_jComboBox.getSelectedItem().toString();
        String Search_Key = search_jTextField.getText();
        if("All".equals(Types_comboBox)){
            Types_comboBox ="%";
        }
        searchDBP searchTable = new searchDBP();

        // Clear table
        searchTable.clearTable(SearchedListTable);
        try {
            searchTable.searchByName(Types_comboBox, Search_Key, SearchedListTable);

        } catch (SQLException ex) {
            Logger.getLogger(nMainFrameP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_search_jButtonActionPerformed

    private void Type_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Type_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Type_jComboBoxActionPerformed

    private void cancel_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_jButtonActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want"
                + " to canel order?", "", JOptionPane.YES_NO_OPTION);
         if ( choice == 0 ) {
                itemManDBP db = new itemManDBP();
                if ( db.cancelOrder()) {
                    JOptionPane.showMessageDialog(null, "order is cancelled", "",
                        JOptionPane.INFORMATION_MESSAGE);
                    //Re-add to inventory
                    int rowC = currentOrderListTable.getRowCount() - 1;
                    System.out.println("row count " + rowC);
                    itemManipulation delm = new itemManipulation();
                        for (int i = 0; i <= rowC; i++) {
                          System.out.println("row to add "+i);
                            System.out.println("rowC val "+ rowC);
                          delm.setQty((int) currentOrderListTable.getModel().getValueAt(i, 4));
                          delm.setItem_serial(Integer.valueOf(currentOrderListTable.getModel().getValueAt(i, 0).toString()));
                          if(db.addStockInventory(delm)){
                            System.out.println("ok dagdag na sa inv" + i);
                                }else{
                                    JOptionPane.showMessageDialog(null, "Problem adding order. "
                                            + "Please contact the administrator.", 
                                            "Something went wrong!", JOptionPane.ERROR_MESSAGE);
                                }
                        }

                  //  refreshSummaryTable();
                  panelSummaryP pSum = new panelSummaryP();
                    try {
                        pSum.refreshSummaryTable(currentOrderListTable);
                        pSum.setTotal(total_jLabel, netTotal_jLabel);
                    } catch (SQLException ex) {
                        System.out.println("deleting "+ ex);
                    }
                    CurrentOrdersP cOrders = CurrentOrdersP.getInstance();
                    cOrders.nullSetOrder_id();
                    cOrders.setCustomer_id(null);
                    setSummaryNull();
                
         } else {
                    
                    JOptionPane.showMessageDialog(null, "Problem deleting order entry. Please contact the administrator.", "Something went wrong!", JOptionPane.ERROR_MESSAGE);
                }
         }
        
    }//GEN-LAST:event_cancel_jButtonActionPerformed

    private void checkout_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkout_jButtonActionPerformed
        // TODO add your handling code here:
        if(orderID_textArea.getText().equals("")){
            JOptionPane.showMessageDialog(null, "There is no transaction", "",
                        JOptionPane.INFORMATION_MESSAGE);
        }else{
        
            CurrentOrdersP cOrders = CurrentOrdersP.getInstance();
            cOrders.setCustomer_id(customerID_textfield.getText());
            cOrders.setOrder_total(total_jLabel.getText());
            cOrders.setNet_total(netTotal_jLabel.getText());
            if(tax_jLabel11.getText().equals("")){
                cOrders.setTax("0.00");
            }else{
                cOrders.setTax(tax_jLabel11.getText());
            }
            

                    java.awt.EventQueue.invokeLater(() -> {
                        new PaymentFrameP(cOrders).setVisible(true);
                    });
                    dispose();
        }
    }//GEN-LAST:event_checkout_jButtonActionPerformed

    private void wprice_jToggleButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_wprice_jToggleButton1StateChanged
        // TODO add your handling code here:
        

    }//GEN-LAST:event_wprice_jToggleButton1StateChanged

    private void wprice_jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wprice_jToggleButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_wprice_jToggleButton1MouseClicked

    private void tax_jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tax_jToggleButton1MouseClicked
        // TODO add your handling code here:
        float netTotal= Float.parseFloat(netTotal_jLabel.getText());
        if(tax_jToggleButton1.isSelected()){
             System.out.println("apply tax");
             //netTotal_jLabel
             //float netTotal= Float.parseFloat(netTotal_jLabel.getText());
             float tax = (float) (netTotal *.12);
             float newNet = netTotal+tax;
             tax_jLabel11.setText(String.valueOf(tax));
             total_jLabel.setText(String.valueOf(newNet));
//tax_jLabel11dxcvgb        
        }else{
            System.out.println("remove tax");
             tax_jLabel11.setText("");
             total_jLabel.setText(String.valueOf(netTotal));
        }
    }//GEN-LAST:event_tax_jToggleButton1MouseClicked

    private void Inventory_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inventory_jButton1ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryP().setVisible(true);
            }
        });
    }//GEN-LAST:event_Inventory_jButton1ActionPerformed

    private void Reports_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reports_jButton2ActionPerformed
        // TODO add your handling code here:
                java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesReportFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_Reports_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Discount_jButton1;
    private javax.swing.JButton Inventory_jButton1;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel OptionPanel;
    private javax.swing.JButton Reports_jButton2;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JTable SearchedListTable;
    private javax.swing.JPanel SummaryPanel;
    private javax.swing.JComboBox<String> Type_jComboBox;
    private javax.swing.JButton add_jButton;
    private javax.swing.JButton cancel_jButton;
    private javax.swing.JButton checkout_jButton;
    public javax.swing.JTable currentOrderListTable;
    private javax.swing.JLabel customerID_jLabel5;
    private javax.swing.JTextField customerID_textfield;
    private javax.swing.JButton del_jButton;
    public javax.swing.JTextField discount_jTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel netTotal_jLabel;
    private javax.swing.JLabel netTotal_jLabel6;
    private javax.swing.JLabel orderID_textArea;
    private javax.swing.JLabel orderid_jLabel4;
    private javax.swing.JTextField qty_textfield;
    private javax.swing.JButton search_jButton;
    private javax.swing.JTextField search_jTextField;
    private javax.swing.JLabel tax_jLabel11;
    private javax.swing.JToggleButton tax_jToggleButton1;
    private javax.swing.JLabel total_jLabel;
    private javax.swing.JToggleButton wprice_jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
