/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import main.CurrentOrdersP;

import main.checkOutInfoDBP;

/**
 *
 * @author victorino manalang
 */
public class PaymentFrameP extends javax.swing.JFrame {

    String ordertype= "cash";
    /**
     * Creates new form PaymentFrame
     */
    public PaymentFrameP() {
        
        initComponents();
         this.setLocationRelativeTo(null);
    }

    public PaymentFrameP(CurrentOrdersP cOrders) {

        initComponents();
        this.setLocationRelativeTo(null);
        refNo_textField.setText("###");
        SummaryPrice.setText(cOrders.getOrder_total());
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        summaryPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        SummaryPrice = new javax.swing.JTextField();
        paymentAmountTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        confirmPayment = new javax.swing.JButton();
        returnOrder = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        CreditR = new javax.swing.JRadioButton();
        GcashR = new javax.swing.JRadioButton();
        cashR = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        refNo_textField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        summaryPanel.setBackground(new java.awt.Color(0, 0, 0));
        summaryPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));
        summaryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 153, 0));
        jLabel2.setText("CUYI INK ENTERPRISE");
        summaryPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 470, 50));

        SummaryPrice.setEditable(false);
        SummaryPrice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        summaryPanel.add(SummaryPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 250, 60));

        paymentAmountTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        summaryPanel.add(paymentAmountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, 250, 60));

        jLabel4.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("Enter Amount:");
        summaryPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, -1, 20));

        confirmPayment.setBackground(new java.awt.Color(204, 255, 255));
        confirmPayment.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        confirmPayment.setForeground(new java.awt.Color(126, 101, 24));
        confirmPayment.setText("Confirm Payment");
        confirmPayment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        confirmPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPaymentActionPerformed(evt);
            }
        });
        summaryPanel.add(confirmPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 360, 220, 70));

        returnOrder.setBackground(new java.awt.Color(255, 255, 204));
        returnOrder.setText("Return to Order Menu");
        returnOrder.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        returnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnOrderActionPerformed(evt);
            }
        });
        summaryPanel.add(returnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 40));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0), 2));

        CreditR.setBackground(new java.awt.Color(255, 255, 204));
        CreditR.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        CreditR.setText("Credit/Debit");
        CreditR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditRActionPerformed(evt);
            }
        });

        GcashR.setBackground(new java.awt.Color(255, 255, 204));
        GcashR.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        GcashR.setText("GCash/PayMaya");
        GcashR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GcashRActionPerformed(evt);
            }
        });

        cashR.setBackground(new java.awt.Color(255, 255, 204));
        cashR.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        cashR.setSelected(true);
        cashR.setText("Cash");
        cashR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashRActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        jLabel5.setText("Pay via:");

        jLabel1.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Transaction No.");

        refNo_textField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(83, 83, 83))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cashR, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GcashR, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CreditR, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(refNo_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(cashR)
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GcashR)
                    .addComponent(refNo_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(CreditR)
                .addGap(59, 59, 59))
        );

        summaryPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 530, 320));

        jLabel7.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setText("TOTAL PRICE:");
        summaryPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(summaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(summaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPaymentActionPerformed
                            // TODO add your handling code here:
        
// order id , customer id ,net total , order total , tax, payment type, payment ref #, date, 
            
            try{
                CurrentOrdersP cOrders = CurrentOrdersP.getInstance();
                Float payment = Float.parseFloat(paymentAmountTextField.getText());
                cOrders.setPaymentAmount(payment);
                cOrders.setPayment_type(ordertype);
                cOrders.setPayment_ref(refNo_textField.getText());

                
                try {
                    
                    if(payment< Float.parseFloat(cOrders.getOrder_total())){
                        JOptionPane.showMessageDialog(null, "Payment insufficient", "Payment", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        
                            checkOutInfoDBP db = new checkOutInfoDBP();
                            if(db.saveOrder() == true){
                                
                                java.awt.EventQueue.invokeLater(() -> {
                                    new ReceiptFrameP().setVisible(true);
                                });
                                setVisible(false);
                            }else{
                                JOptionPane.showMessageDialog(null, "Payment not Succesful!", "Payment", JOptionPane.INFORMATION_MESSAGE);
                            }
                            //Reseting current order object for new order

                    }

            }catch (NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Enter proper amount!", "Payment", JOptionPane.INFORMATION_MESSAGE);
                System.out.println( "una "+e);
            }
        }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Enter payment amount!", "Payment", JOptionPane.INFORMATION_MESSAGE);
                
        }
    }//GEN-LAST:event_confirmPaymentActionPerformed

    private void returnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnOrderActionPerformed
                    java.awt.EventQueue.invokeLater(() -> {
                        new nMainFrameP().setVisible(true);
                    });
        setVisible(false);
        
    }//GEN-LAST:event_returnOrderActionPerformed

    private void GcashRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GcashRActionPerformed
        // TODO add your handling code here:
        ordertype= "mobile";
        cashR.setSelected(false);
        CreditR.setSelected(false);
    }//GEN-LAST:event_GcashRActionPerformed

    private void cashRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashRActionPerformed
        // TODO add your handling code here:
        ordertype= "cash";
        GcashR.setSelected(false);
        CreditR.setSelected(false);
    }//GEN-LAST:event_cashRActionPerformed

    private void CreditRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditRActionPerformed
        // TODO add your handling code here:
        ordertype= "card";
         GcashR.setSelected(false);
         cashR.setSelected(false);
    }//GEN-LAST:event_CreditRActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CreditR;
    private javax.swing.JRadioButton GcashR;
    private javax.swing.JTextField SummaryPrice;
    private javax.swing.JRadioButton cashR;
    private javax.swing.JButton confirmPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField paymentAmountTextField;
    private javax.swing.JTextField refNo_textField;
    private javax.swing.JButton returnOrder;
    private javax.swing.JPanel summaryPanel;
    // End of variables declaration//GEN-END:variables
}
